GET http://localhost:3000/
Content-Type: application/json

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Mau31",
    "password": "Uvabombom31"
}

###
PATCH  http://localhost:3000/updatePassword
Content-Type: application/json
Cookie:access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJNYXUzMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NzExOTU4NCwiZXhwIjoxNzU3MTIwNzg0fQ.4oGgFx0ONG3zWBBZtNGt-7R6eCon3mlNtJqZOY26t78

{
    "newPassword": "Uvabombom32",
    "password": "Uvabombom31"
}

###
GET http://localhost:3000/products

